##Technical Validation
##BC Wildfire PSTA Fire Density 

## Step 1: Call libraries

library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
library(terra)
library(sf)
library(tidyterra)

## Step 2: Load data

#harmonized pstafire data
pstafire <- rast("Products/2021_bcrast_pstafire.nc")

#raw pstafire data
pstafire_raw <- vect("Data/PSTAFire/PROT_PSTA_FIRE_STRT_DENSITY_SP/PROTPSTAFI_polygon.shp")

#terrestrial extent data
ext <- st_read("Products/2025_bcvect_extent.gpkg")

#load documentation
docs <- read.csv("Documentation/2021_bcrast_pstafire.csv")

## Step 3: Iterate simple random sampling of datasets

#create results dataframe
results <- data.frame(PCC = vector(mode = "numeric", length = 30))

#iterate sampling process 30 times
for(i in 1:30){
  #generate sample within extent
  sample <- ext %>% st_sample(size = 8100, type = "random") %>% vect()

  #annotate sampling points to rejoin data
  sample$ID = 1:nrow(sample)

  #extract dem values
  vals <- terra::extract(pstafire, sample)

  #reproject sample locations to crs of raw data
  sample_raw <- sample %>% project(crs(pstafire_raw))

  #extract raw dem values
  vals_raw <- as.data.frame(terra::intersect(sample_raw, pstafire_raw))

  #classify variables in raw extract using documentation
  vals_raw <- vals_raw %>% left_join(docs) %>% 
    rename(fire_density_raw = fire_density) %>% select(ID, fire_density_raw)

  #join dataframes
  vals <- vals %>% left_join(vals_raw)
  
  #filter out NA values generated by OOB sample points or NA values in the original layer
  vals <- vals %>% filter(!is.na(fire_density), !is.na(fire_density_raw))

  #calculate accuracy
  vals <- vals %>% mutate(correct = as.numeric(fire_density == fire_density_raw))

  #store PCC
  results$PCC[i] <- sum(vals$correct)/nrow(vals)
}

## Step 3: Process and analyze extracted data

#transform probabilities using logit
results$logitPCC <- log(results$PCC/(1-results$PCC))

#save data
write.csv(results, "Data/Validation/validation_2021_bcrast_pstafire.csv", row.names = FALSE)

#calculate confidence interval
logitmean <- mean(results$logitPCC)
logitsd <- sd(results$logitPCC)
logitci <- c(logitmean - 1.96*(logitsd/sqrt(30)), logitmean + 1.96*(logitsd/sqrt(30)))

#transform back to percentages
mean <- 1/(1+exp(-logitmean))
ci <- 1/(1+exp(-logitci))
