##Technical Validation
##BEC Map

## Step 1: Call libraries

library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
library(terra)
library(sf)
library(tidyterra)

## Step 2: Load data

#harmonized BEC data
bec <- rast("Products/2021_bcrast_bec.nc")

#raw BEC data
bec_raw <- vect("Data/BEC/BEC_BIOGEOCLIMATIC_POLY/BEC_POLY_polygon.shp")

#terrestrial extent data
ext <- st_read("Products/2025_bcvect_extent.gpkg")

#documentation
docs <- read_csv("Documentation/2021_bcrast_bec.csv")

## Step 3: Iterate simple random sampling of datasets

#create results dataframe
results <- data.frame(PCC = vector(mode = "numeric", length = 30))

#iterate sampling process 30 times
for(i in 1:30){
  #generate sample within extent of dem
  sample <- ext %>% st_sample(size = 8100, type = "random") %>% vect()
  
  #annotate sampling points to rejoin data
  sample$ID = 1:nrow(sample)
  
  #extract dem values
  vals <- terra::extract(bec, sample)
  
  #reproject sample locations to crs of raw data
  sample_raw <- sample %>% project(crs(bec_raw))
  
  #extract raw dem values
  vals_raw <- as.data.frame(terra::intersect(sample_raw, bec_raw))
  
  #create Z-SZ identifier to left join documentation
  vals_raw$Z_SZ <- paste0(vals_raw$ZONE, "-", vals_raw$SUBZONE)
  
  #left join documentation
  vals_raw <- vals_raw %>% left_join(docs, by = "Z_SZ")
  
  #rename variables in raw extract
  vals_raw <- vals_raw %>% rename(beccode_raw = beccode) %>% select(ID, beccode_raw)
  
  #join dataframes
  vals <- vals %>% left_join(vals_raw)
  
  #filter out NA values generated by OOB sample points or NA values in the original layer
  vals <- vals %>% filter(!is.na(beccode), !is.na(beccode_raw))
  
  #calculate accuracy
  vals <- vals %>% mutate(correct = as.numeric(beccode == beccode_raw))
  
  #store PCC
  results$PCC[i] <- sum(vals$correct)/nrow(vals)
}

## Step 3: Process and analyze extracted data

#transform probabilities using logit
results$logitPCC <- log(results$PCC/(1-results$PCC))

#save data
write.csv(results, "Data/Validation/validation_2021_bcrast_bec.csv", row.names = FALSE)

#calculate confidence interval
logitmean <- mean(results$logitPCC)
logitsd <- sd(results$logitPCC)
logitci <- c(logitmean - 1.96*(logitsd/sqrt(30)), logitmean + 1.96*(logitsd/sqrt(30)))

#transform back to percentages
mean <- 1/(1+exp(-logitmean))
ci <- 1/(1+exp(-logitci))
