##Technical Validation
##2022 Forest Age

## Step 1: Call libraries

library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
library(terra)
library(sf)
library(tidyterra)

## Step 2: Load data

#harmonized pstahead data
age <- rast("Products/2022_bcrast_forestage.nc")

#raw pstahead data
age_raw <- rast("Data/ForestAge/CA_forest_age_2022.tif")

#terrestrial extent data
ext <- st_read("Products/2025_bcvect_extent.gpkg")

## Step 3: Iterate simple random sampling of datasets

#create results dataframe
results <- data.frame(PCC = vector(mode = "numeric", length = 30))

#iterate sampling process 30 times
for(i in 1:30){
  #generate sample within extent of dem
  sample <- ext %>% st_sample(size = 8100, type = "random") %>% vect()
  
  #annotate sampling points to rejoin data
  sample$ID = 1:nrow(sample)
  
  #extract dem values
  vals <- terra::extract(age, sample)
  
  #reproject sample locations to crs of raw data
  sample_raw <- sample %>% project(crs(age_raw))
  
  #extract raw dem values
  vals_raw <- terra::extract(age_raw, sample_raw)
  
  #rename variables in raw extract
  vals_raw <- vals_raw %>% rename(forestage_raw = CA_forest_age_2022) %>% 
    select(ID, forestage_raw)
  
  #join dataframes
  vals <- vals %>% left_join(vals_raw)
  
  #filter out NA values generated by OOB sample points or NA values in the original layer
  vals <- vals %>% filter(!is.na(forestage), !is.na(forestage_raw))
  
  #convert forestage year to raw value
  vals$forestage <- 2022-vals$forestage
  
  #convert NA value to correct numeric identifier (2022 to 255)
  vals$forestage[vals$forestage == 2022] <- 255
  
  #calculate accuracy
  vals <- vals %>% mutate(correct = as.numeric(forestage == forestage_raw))
  
  #store PCC
  results$PCC[i] <- sum(vals$correct)/nrow(vals)
}

## Step 3: Process and analyze extracted data

#transform probabilities using logit
results$logitPCC <- log(results$PCC/(1-results$PCC))

#save data
write.csv(results, "Data/Validation/validation_2020_bcrast_landcover.csv", row.names = FALSE)

#calculate confidence interval
logitmean <- mean(results$logitPCC)
logitsd <- sd(results$logitPCC)
logitci <- c(logitmean - 1.96*(logitsd/sqrt(30)), logitmean + 1.96*(logitsd/sqrt(30)))

#transform back to percentages
mean <- 1/(1+exp(-logitmean))
ci <- 1/(1+exp(-logitci))
