##Technical Validation
##2010 Land Cover

## Step 1: Call libraries

library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
library(terra)
library(sf)
library(tidyterra)

## Step 2: Load data

#harmonized pstahead data
lco <- rast("Products/2010_bcrast_landcover.nc")

#raw pstahead data
lco_raw <- rast("Data/2010LandCover/landcover-2010-classification.tif")

#terrestrial extent data
ext <- st_read("Products/2025_bcvect_extent.gpkg")

## Step 3: Iterate simple random sampling of datasets

#create results dataframe
results <- data.frame(PCC = vector(mode = "numeric", length = 30))

#iterate sampling process 30 times
for(i in 1:30){
  #generate sample within extent of dem
  sample <- ext %>% st_sample(size = 8100, type = "random") %>% vect()
  
  #annotate sampling points to rejoin data
  sample$ID = 1:nrow(sample)
  
  #extract dem values
  vals <- terra::extract(lco, sample)
  
  #reproject sample locations to crs of raw data
  sample_raw <- sample %>% project(crs(lco_raw))
  
  #extract raw dem values
  vals_raw <- terra::extract(lco_raw, sample_raw)
  
  #rename variables in raw extract
  vals_raw <- vals_raw %>% rename(landcover_raw = Canada2010) %>% 
    select(ID, landcover_raw)
  
  #join dataframes
  vals <- vals %>% left_join(vals_raw)
  
  #filter out NA values generated by OOB sample points or NA values in the original layer
  vals <- vals %>% filter(!is.na(landcover), !is.na(landcover_raw))
  
  #calculate accuracy
  vals <- vals %>% mutate(correct = as.numeric(landcover == landcover_raw))
  
  #store PCC
  results$PCC[i] <- sum(vals$correct)/nrow(vals)
}

## Step 3: Process and analyze extracted data

#transform probabilities using logit
results$logitPCC <- log(results$PCC/(1-results$PCC))

#save data
write.csv(results, "Data/Validation/validation_2010_bcrast_landcover.csv", row.names = FALSE)

#calculate confidence interval
logitmean <- mean(results$logitPCC)
logitsd <- sd(results$logitPCC)
logitci <- c(logitmean - 1.96*(logitsd/sqrt(30)), logitmean + 1.96*(logitsd/sqrt(30)))

#transform back to percentages
mean <- 1/(1+exp(-logitmean))
ci <- 1/(1+exp(-logitci))
