##Technical Validation
##dNBR Values (2026)

## Step 1: Call libraries

library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
library(terra)
library(sf)
library(tidyterra)

## Step 2: Load data

#harmonized data
dnbr <- rast("Products/2026_bcrast_dnbr.nc")

#raw data
dnbr_raw <- rast("Data/dNBR/CanLaBS_1985_2024_v20260121.tif")

#terrestrial extent data
ext <- st_read("Products/2020_bcvect_extent.gpkg")

## Step 3: Iterate simple random sampling of datasets

#create results dataframe
results <- data.frame(RMSE = vector(mode = "numeric", length = 30),
                      MAE = vector(mode = "numeric", length = 30))

#iterate sampling process 30 times
for(i in 1:30){
  #generate sample within extent
  sample <- ext %>% st_sample(size = 8100, type = "random") %>% vect()
  
  #annotate sampling points to rejoin data
  sample$ID = 1:nrow(sample)
  
  #extract values
  vals <- terra::extract(dnbr, sample)
  
  #reproject sample locations to crs of raw data
  sample_raw <- sample %>% project(crs(dnbr_raw))
  
  #extract raw values
  vals_raw <- terra::extract(dnbr_raw, sample_raw)
  
  #rename variables in raw extract
  vals_raw <- vals_raw %>% rename(dnbr_raw = `CanLaBS_1985_2024_v20260121`) %>% 
    select(ID, dnbr_raw)
  
  #join dataframes
  vals <- vals %>% left_join(vals_raw)
  
  #filter out NA values generated by OOB sample points or NA values in the original layer
  vals <- vals %>% filter(!is.na(dnbr), !is.na(dnbr_raw))
  
  #calculate error, SE, and AE for each value
  vals <- vals %>% mutate(error = dnbr - dnbr_raw,
                          SE = error^2,
                          AE = abs(error))
  
  #calculate RMSE
  results$RMSE[i] <- sqrt(sum(vals$SE))/sqrt(nrow(vals))
  
  #calculate MAE
  results$MAE[i] <- sum(vals$AE)/nrow(vals)
}

## Step 3: Process and analyze extracted data

#save data
write.csv(results, "Data/Validation/validation_2026_bcrast_dnbr.csv", row.names = FALSE)

#calculate RMSE confidence interval
RMSEmean <- mean(results$RMSE)
RMSEsd <- sd(results$RMSE)
RMSEci <- c(RMSEmean - 1.96*(RMSEsd/sqrt(30)), RMSEmean + 1.96*(RMSEsd/sqrt(30)))

#calculate MAE confidence interval
MAEmean <- mean(results$MAE)
MAEsd <- sd(results$MAE)
MAEci <- c(MAEmean - 1.96*(MAEsd/sqrt(30)), MAEmean + 1.96*(MAEsd/sqrt(30)))
