##Technical Validation
##Forest Height Standard Deviation (2022)

## Step 1: Call libraries

library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
library(terra)
library(sf)
library(tidyterra)

## Step 2: Load data

#harmonized data
height <- rast("Products/2022_bcrast_stddevheight.nc")

#raw data
height_raw <- rast("Data/HeightStdDev/CA_elev_stddev_2022.tif")

#terrestrial extent data
ext <- st_read("Products/2025_bcvect_extent.gpkg")

## Step 3: Iterate simple random sampling of datasets

#create results dataframe
results <- data.frame(RMSE = vector(mode = "numeric", length = 30),
                      MAE = vector(mode = "numeric", length = 30))

#iterate sampling process 30 times
for(i in 1:30){
  #generate sample within extent of dem
  sample <- ext %>% st_sample(size = 8100, type = "random") %>% vect()
  
  #annotate sampling points to rejoin data
  sample$ID = 1:nrow(sample)
  
  #extract dem values
  vals <- terra::extract(height, sample)
  
  #reproject sample locations to crs of raw data
  sample_raw <- sample %>% project(crs(height_raw))
  
  #extract raw dem values
  vals_raw <- terra::extract(height_raw, sample_raw)
  
  #rename variables in raw extract
  vals_raw <- vals_raw %>% rename(height_raw = `Band 1`) %>% 
    select(ID, height_raw)
  
  #join dataframes
  vals <- vals %>% left_join(vals_raw)
  
  #filter out NA values generated by OOB sample points or NA values in the original layer
  vals <- vals %>% filter(!is.na(height), !is.na(height_raw))
  
  #calculate error, SE, and AE for each value
  vals <- vals %>% mutate(error = height - height_raw,
                          SE = error^2,
                          AE = abs(error))
  
  #calculate RMSE
  results$RMSE[i] <- sqrt(sum(vals$SE))/sqrt(nrow(vals))
  
  #calculate MAE
  results$MAE[i] <- sum(vals$AE)/nrow(vals)
}

## Step 3: Process and analyze extracted data

#save data
write.csv(results, "Data/Validation/validation_2022_bcrast_stddevheight.csv", row.names = FALSE)

#calculate RMSE confidence interval
RMSEmean <- mean(results$RMSE)
RMSEsd <- sd(results$RMSE)
RMSEci <- c(RMSEmean - 1.96*(RMSEsd/sqrt(30)), RMSEmean + 1.96*(RMSEsd/sqrt(30)))

#calculate MAE confidence interval
MAEmean <- mean(results$MAE)
MAEsd <- sd(results$MAE)
MAEci <- c(MAEmean - 1.96*(MAEsd/sqrt(30)), MAEmean + 1.96*(MAEsd/sqrt(30)))
