##Technical Validation
##Digital Elevation Model for British Columbia - CDED - 1:250,000

## Step 1: Call libraries

library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
library(terra)
library(sf)
library(tidyterra)
library(bcmaps)

## Step 2: Load data

#harmonized dem data
dem <- rast("Products/2014_bcrast_dem.nc")

#terrestrial extent data
ext <- st_read("Products/2025_bcvect_extent.gpkg")

#raw DEM data from bcmaps, to avoid a mosaic of raw letterblocks
dem_raw <- cded_terra(aoi = ext)

## Step 3: Iterate simple random sampling of datasets

#create results dataframe
results <- data.frame(RMSE = vector(mode = "numeric", length = 30),
                      MAE = vector(mode = "numeric", length = 30))

#iterate sampling process 30 times
for(i in 1:30){
  #generate sample within extent of dem
  sample <- ext %>% st_sample(size = 8100, type = "random") %>% vect()

  #extract dem values
  vals <- terra::extract(dem, sample)

  #reproject sample locations to crs of raw data
  sample_raw <- sample %>% project(crs(dem_raw))

  #extract raw dem values
  vals_raw <- terra::extract(dem_raw, sample_raw)

  #rename variables in raw extract
  vals_raw <- vals_raw %>% rename(elevation_raw = elevation)

  #join dataframes
  vals <- vals %>% left_join(vals_raw)

  #calculate error, SE, and AE for each value
  vals <- vals %>% mutate(error = elevation - elevation_raw,
                              SE = error^2,
                              AE = abs(error))
  
  #filter out NA values generated by OOB sample points or NA values in the original layer
  vals <- vals %>% filter(!is.na(elevation), !is.na(elevation_raw))

  #calculate RMSE
  results$RMSE[i] <- sqrt(sum(vals$SE))/sqrt(nrow(vals))

  #calculate MAE
  results$MAE[i] <- sum(vals$AE)/nrow(vals)
}
## Step 3: Process and analyze extracted data

#save data
write.csv(results, "Data/Validation/validation_2014_bcrast_dem.csv", row.names = FALSE)

#calculate RMSE confidence interval
RMSEmean <- mean(results$RMSE)
RMSEsd <- sd(results$RMSE)
RMSEci <- c(RMSEmean - 1.96*(RMSEsd/sqrt(30)), RMSEmean + 1.96*(RMSEsd/sqrt(30)))

#calculate MAE confidence interval
MAEmean <- mean(results$MAE)
MAEsd <- sd(results$MAE)
MAEci <- c(MAEmean - 1.96*(MAEsd/sqrt(30)), MAEmean + 1.96*(MAEsd/sqrt(30)))
