##Technical Validation
##Canadian Forest Fire Danger Rating System (CFFDRS) Fire Behaviour Prediction (FBP) Fuel Types 2024, 30 M

## Step 1: Call libraries

library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
library(terra)
library(sf)
library(tidyterra)

## Step 2: Load data

#harmonized pstahead data
fuels <- rast("Products/2024_bcrast_fueltypes.nc")

#raw pstahead data
fuels_raw <- rast("Data/Fueltypes/FBP_Canada_30m_3978_22052024_forRelease.tif")

#terrestrial extent data
ext <- st_read("Products/2025_bcvect_extent.gpkg")

## Step 3: Iterate simple random sampling of datasets

#create results dataframe
results <- data.frame(PCC = vector(mode = "numeric", length = 30))

#iterate sampling process 30 times
for(i in 1:30){
  #generate sample within extent of dem
  sample <- ext %>% st_sample(size = 8100, type = "random") %>% vect()
  
  #annotate sampling points to rejoin data
  sample$ID = 1:nrow(sample)
  
  #extract dem values
  vals <- terra::extract(fuels, sample)
  
  #reproject sample locations to crs of raw data
  sample_raw <- sample %>% project(crs(fuels_raw))
  
  #extract raw dem values
  vals_raw <- terra::extract(fuels_raw, sample_raw)
  
  #rename variables in raw extract
  vals_raw <- vals_raw %>% rename(fueltype_raw = `Canadian FBP Fuel Types, 30m, May 22nd, 2024`) %>% 
    select(ID, fueltype_raw)
  
  #join dataframes
  vals <- vals %>% left_join(vals_raw)
  
  #filter out NA values generated by OOB sample points or NA values in the original layer
  vals <- vals %>% filter(!is.na(fueltype), !is.na(fueltype_raw))
  
  #calculate accuracy
  vals <- vals %>% mutate(correct = as.numeric(fueltype == fueltype_raw))
  
  #store PCC
  results$PCC[i] <- sum(vals$correct)/nrow(vals)
}

## Step 3: Process and analyze extracted data

#transform probabilities using logit
results$logitPCC <- log(results$PCC/(1-results$PCC))

#save data
write.csv(results, "Data/Validation/validation_2024_bcrast_fueltypes.csv", row.names = FALSE)

#calculate confidence interval
logitmean <- mean(results$logitPCC)
logitsd <- sd(results$logitPCC)
logitci <- c(logitmean - 1.96*(logitsd/sqrt(30)), logitmean + 1.96*(logitsd/sqrt(30)))

#transform back to percentages
mean <- 1/(1+exp(-logitmean))
ci <- 1/(1+exp(-logitci))
