##Technical Validation
##NBAC Year (2026)

## Step 1: Call libraries

library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
library(terra)
library(sf)
library(tidyterra)

## Step 2: Load data

#harmonized data
nbacyear <- rast("Products/2026_bcrast_nbacyear.nc")

#raw data
nbacyear_raw <- rast("Data/NBACYear/NBAC_MRB_1972to2024_reproj.tif")

#terrestrial extent data
ext <- st_read("Products/2020_bcvect_extent.gpkg")

## Step 3: Iterate simple random sampling of datasets

#create results dataframe
results <- data.frame(PCC = vector(mode = "numeric", length = 30))

#iterate sampling process 30 times
for(i in 1:30){
  #generate sample within extent
  sample <- ext %>% st_sample(size = 8100, type = "random") %>% vect()
  
  #annotate sampling points to rejoin data
  sample$ID = 1:nrow(sample)
  
  #extract values
  vals <- terra::extract(nbacyear, sample)
  
  #reproject sample locations to crs of raw data
  sample_raw <- sample %>% project(crs(nbacyear_raw))
  
  #extract raw values
  vals_raw <- terra::extract(nbacyear_raw, sample_raw)
  
  #rename variables in raw extract
  vals_raw <- vals_raw %>% rename(burnyear_raw = `NBAC_MRB_1972to2024_reproj`) %>% 
    select(ID, burnyear_raw)
  
  #join dataframes
  vals <- vals %>% left_join(vals_raw)
  
  #filter out NA values generated by OOB sample points or NA values in the original layer
  vals <- vals %>% filter(!is.na(burnyear), !is.na(burnyear_raw))
  
  #calculate accuracy
  vals <- vals %>% mutate(correct = as.numeric(burnyear == burnyear_raw))
  
  #store PCC
  results$PCC[i] <- sum(vals$correct)/nrow(vals)
}

## Step 3: Process and analyze extracted data

#transform probabilities using logit
results$logitPCC <- log(results$PCC/(1-results$PCC))

#save data
write.csv(results, "Data/Validation/validation_2026_bcrast_nbacyear.csv", row.names = FALSE)

#calculate confidence interval
logitmean <- mean(results$logitPCC)
logitsd <- sd(results$logitPCC)
logitci <- c(logitmean - 1.96*(logitsd/sqrt(30)), logitmean + 1.96*(logitsd/sqrt(30)))

#transform back to percentages
mean <- 1/(1+exp(-logitmean))
ci <- 1/(1+exp(-logitci))
